//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockAndPass.WebService.LiquidacionWR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.mc.com.co/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BlockAndPass.WebService.LiquidacionWR.Liquidacion_Request))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Liquidacion_Request", Namespace="http://www.MillensCorp.com/types/")]
    [System.SerializableAttribute()]
    public partial class Liquidacion_Request : BlockAndPass.WebService.LiquidacionWR.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bMensualidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bReposicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sConveniosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sIdtarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sSecuenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bMensualidad {
            get {
                return this.bMensualidadField;
            }
            set {
                if ((this.bMensualidadField.Equals(value) != true)) {
                    this.bMensualidadField = value;
                    this.RaisePropertyChanged("bMensualidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bReposicion {
            get {
                return this.bReposicionField;
            }
            set {
                if ((this.bReposicionField.Equals(value) != true)) {
                    this.bReposicionField = value;
                    this.RaisePropertyChanged("bReposicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iTipoVehiculo {
            get {
                return this.iTipoVehiculoField;
            }
            set {
                if ((this.iTipoVehiculoField.Equals(value) != true)) {
                    this.iTipoVehiculoField = value;
                    this.RaisePropertyChanged("iTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sConvenios {
            get {
                return this.sConveniosField;
            }
            set {
                if ((object.ReferenceEquals(this.sConveniosField, value) != true)) {
                    this.sConveniosField = value;
                    this.RaisePropertyChanged("sConvenios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sIdtarjeta {
            get {
                return this.sIdtarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.sIdtarjetaField, value) != true)) {
                    this.sIdtarjetaField = value;
                    this.RaisePropertyChanged("sIdtarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sSecuencia {
            get {
                return this.sSecuenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.sSecuenciaField, value) != true)) {
                    this.sSecuenciaField = value;
                    this.RaisePropertyChanged("sSecuencia");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.mc.com.co/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BlockAndPass.WebService.LiquidacionWR.Liquidacion_Response))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlockAndPass.WebService.LiquidacionWR.AcknowledgeType AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IdInsertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsAffectedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlockAndPass.WebService.LiquidacionWR.AcknowledgeType Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((this.CorrelationIdField.Equals(value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IdInsert {
            get {
                return this.IdInsertField;
            }
            set {
                if ((this.IdInsertField.Equals(value) != true)) {
                    this.IdInsertField = value;
                    this.RaisePropertyChanged("IdInsert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationIdField, value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsAffected {
            get {
                return this.RowsAffectedField;
            }
            set {
                if ((this.RowsAffectedField.Equals(value) != true)) {
                    this.RowsAffectedField = value;
                    this.RaisePropertyChanged("RowsAffected");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Liquidacion_Response", Namespace="http://www.MillensCorp.com/types/")]
    [System.SerializableAttribute()]
    public partial class Liquidacion_Response : BlockAndPass.WebService.LiquidacionWR.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlockAndPass.WebService.LiquidacionWR.ServiceDtoLiquidacion oDtoLiquidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlockAndPass.WebService.LiquidacionWR.ServiceDtoLiquidacion oDtoLiquidacionCascoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlockAndPass.WebService.LiquidacionWR.ServiceDtoTransaccion oDtoTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlockAndPass.WebService.LiquidacionWR.ServiceDtoDatosLiquidacion[] olstDtoLiquidacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlockAndPass.WebService.LiquidacionWR.ServiceDtoLiquidacion oDtoLiquidacion {
            get {
                return this.oDtoLiquidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.oDtoLiquidacionField, value) != true)) {
                    this.oDtoLiquidacionField = value;
                    this.RaisePropertyChanged("oDtoLiquidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlockAndPass.WebService.LiquidacionWR.ServiceDtoLiquidacion oDtoLiquidacionCasco {
            get {
                return this.oDtoLiquidacionCascoField;
            }
            set {
                if ((object.ReferenceEquals(this.oDtoLiquidacionCascoField, value) != true)) {
                    this.oDtoLiquidacionCascoField = value;
                    this.RaisePropertyChanged("oDtoLiquidacionCasco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlockAndPass.WebService.LiquidacionWR.ServiceDtoTransaccion oDtoTransaccion {
            get {
                return this.oDtoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.oDtoTransaccionField, value) != true)) {
                    this.oDtoTransaccionField = value;
                    this.RaisePropertyChanged("oDtoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlockAndPass.WebService.LiquidacionWR.ServiceDtoDatosLiquidacion[] olstDtoLiquidacion {
            get {
                return this.olstDtoLiquidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.olstDtoLiquidacionField, value) != true)) {
                    this.olstDtoLiquidacionField = value;
                    this.RaisePropertyChanged("olstDtoLiquidacion");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeType", Namespace="http://www.mc.com.co/types/")]
    public enum AcknowledgeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDtoLiquidacion", Namespace="http://www.MillensCorp.com/types/")]
    [System.SerializableAttribute()]
    public partial class ServiceDtoLiquidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstacionamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdConvenioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdConvenio2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdConvenio3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdEstacionamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdEventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCobroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estacionamiento {
            get {
                return this.EstacionamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstacionamientoField, value) != true)) {
                    this.EstacionamientoField = value;
                    this.RaisePropertyChanged("Estacionamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdAutorizacion {
            get {
                return this.IdAutorizacionField;
            }
            set {
                if ((this.IdAutorizacionField.Equals(value) != true)) {
                    this.IdAutorizacionField = value;
                    this.RaisePropertyChanged("IdAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdConvenio {
            get {
                return this.IdConvenioField;
            }
            set {
                if ((this.IdConvenioField.Equals(value) != true)) {
                    this.IdConvenioField = value;
                    this.RaisePropertyChanged("IdConvenio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdConvenio2 {
            get {
                return this.IdConvenio2Field;
            }
            set {
                if ((this.IdConvenio2Field.Equals(value) != true)) {
                    this.IdConvenio2Field = value;
                    this.RaisePropertyChanged("IdConvenio2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdConvenio3 {
            get {
                return this.IdConvenio3Field;
            }
            set {
                if ((this.IdConvenio3Field.Equals(value) != true)) {
                    this.IdConvenio3Field = value;
                    this.RaisePropertyChanged("IdConvenio3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstacionamiento {
            get {
                return this.IdEstacionamientoField;
            }
            set {
                if ((this.IdEstacionamientoField.Equals(value) != true)) {
                    this.IdEstacionamientoField = value;
                    this.RaisePropertyChanged("IdEstacionamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEvento {
            get {
                return this.IdEventoField;
            }
            set {
                if ((this.IdEventoField.Equals(value) != true)) {
                    this.IdEventoField = value;
                    this.RaisePropertyChanged("IdEvento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTarifa {
            get {
                return this.IdTarifaField;
            }
            set {
                if ((this.IdTarifaField.Equals(value) != true)) {
                    this.IdTarifaField = value;
                    this.RaisePropertyChanged("IdTarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTipoPago {
            get {
                return this.IdTipoPagoField;
            }
            set {
                if ((this.IdTipoPagoField.Equals(value) != true)) {
                    this.IdTipoPagoField = value;
                    this.RaisePropertyChanged("IdTipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTipoVehiculo {
            get {
                return this.IdTipoVehiculoField;
            }
            set {
                if ((this.IdTipoVehiculoField.Equals(value) != true)) {
                    this.IdTipoVehiculoField = value;
                    this.RaisePropertyChanged("IdTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCobro {
            get {
                return this.TipoCobroField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCobroField, value) != true)) {
                    this.TipoCobroField = value;
                    this.RaisePropertyChanged("TipoCobro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPago {
            get {
                return this.TipoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPagoField, value) != true)) {
                    this.TipoPagoField = value;
                    this.RaisePropertyChanged("TipoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVehiculo {
            get {
                return this.TipoVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVehiculoField, value) != true)) {
                    this.TipoVehiculoField = value;
                    this.RaisePropertyChanged("TipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDtoTransaccion", Namespace="http://www.MillensCorp.com/types/")]
    [System.SerializableAttribute()]
    public partial class ServiceDtoTransaccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarrilEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CarrilSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Convenio1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Convenio2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Convenio3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CortesiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdAutorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdEstacionamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuloSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SincronizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SincronizacionPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SincronizacionSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorRecibidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cambio {
            get {
                return this.CambioField;
            }
            set {
                if ((this.CambioField.Equals(value) != true)) {
                    this.CambioField = value;
                    this.RaisePropertyChanged("Cambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarrilEntrada {
            get {
                return this.CarrilEntradaField;
            }
            set {
                if ((this.CarrilEntradaField.Equals(value) != true)) {
                    this.CarrilEntradaField = value;
                    this.RaisePropertyChanged("CarrilEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CarrilSalida {
            get {
                return this.CarrilSalidaField;
            }
            set {
                if ((this.CarrilSalidaField.Equals(value) != true)) {
                    this.CarrilSalidaField = value;
                    this.RaisePropertyChanged("CarrilSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Convenio1 {
            get {
                return this.Convenio1Field;
            }
            set {
                if ((this.Convenio1Field.Equals(value) != true)) {
                    this.Convenio1Field = value;
                    this.RaisePropertyChanged("Convenio1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Convenio2 {
            get {
                return this.Convenio2Field;
            }
            set {
                if ((this.Convenio2Field.Equals(value) != true)) {
                    this.Convenio2Field = value;
                    this.RaisePropertyChanged("Convenio2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Convenio3 {
            get {
                return this.Convenio3Field;
            }
            set {
                if ((this.Convenio3Field.Equals(value) != true)) {
                    this.Convenio3Field = value;
                    this.RaisePropertyChanged("Convenio3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cortesia {
            get {
                return this.CortesiaField;
            }
            set {
                if ((this.CortesiaField.Equals(value) != true)) {
                    this.CortesiaField = value;
                    this.RaisePropertyChanged("Cortesia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrada {
            get {
                return this.FechaEntradaField;
            }
            set {
                if ((this.FechaEntradaField.Equals(value) != true)) {
                    this.FechaEntradaField = value;
                    this.RaisePropertyChanged("FechaEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaSalida {
            get {
                return this.FechaSalidaField;
            }
            set {
                if ((this.FechaSalidaField.Equals(value) != true)) {
                    this.FechaSalidaField = value;
                    this.RaisePropertyChanged("FechaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdAutorizado {
            get {
                return this.IdAutorizadoField;
            }
            set {
                if ((this.IdAutorizadoField.Equals(value) != true)) {
                    this.IdAutorizadoField = value;
                    this.RaisePropertyChanged("IdAutorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstacionamiento {
            get {
                return this.IdEstacionamientoField;
            }
            set {
                if ((this.IdEstacionamientoField.Equals(value) != true)) {
                    this.IdEstacionamientoField = value;
                    this.RaisePropertyChanged("IdEstacionamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTarjeta {
            get {
                return this.IdTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTarjetaField, value) != true)) {
                    this.IdTarjetaField = value;
                    this.RaisePropertyChanged("IdTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoVehiculo {
            get {
                return this.IdTipoVehiculoField;
            }
            set {
                if ((this.IdTipoVehiculoField.Equals(value) != true)) {
                    this.IdTipoVehiculoField = value;
                    this.RaisePropertyChanged("IdTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTransaccion {
            get {
                return this.IdTransaccionField;
            }
            set {
                if ((this.IdTransaccionField.Equals(value) != true)) {
                    this.IdTransaccionField = value;
                    this.RaisePropertyChanged("IdTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuloEntrada {
            get {
                return this.ModuloEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloEntradaField, value) != true)) {
                    this.ModuloEntradaField = value;
                    this.RaisePropertyChanged("ModuloEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuloSalida {
            get {
                return this.ModuloSalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuloSalidaField, value) != true)) {
                    this.ModuloSalidaField = value;
                    this.RaisePropertyChanged("ModuloSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlacaEntrada {
            get {
                return this.PlacaEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaEntradaField, value) != true)) {
                    this.PlacaEntradaField = value;
                    this.RaisePropertyChanged("PlacaEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlacaSalida {
            get {
                return this.PlacaSalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaSalidaField, value) != true)) {
                    this.PlacaSalidaField = value;
                    this.RaisePropertyChanged("PlacaSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sincronizacion {
            get {
                return this.SincronizacionField;
            }
            set {
                if ((this.SincronizacionField.Equals(value) != true)) {
                    this.SincronizacionField = value;
                    this.RaisePropertyChanged("Sincronizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SincronizacionPago {
            get {
                return this.SincronizacionPagoField;
            }
            set {
                if ((this.SincronizacionPagoField.Equals(value) != true)) {
                    this.SincronizacionPagoField = value;
                    this.RaisePropertyChanged("SincronizacionPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SincronizacionSalida {
            get {
                return this.SincronizacionSalidaField;
            }
            set {
                if ((this.SincronizacionSalidaField.Equals(value) != true)) {
                    this.SincronizacionSalidaField = value;
                    this.RaisePropertyChanged("SincronizacionSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorRecibido {
            get {
                return this.ValorRecibidoField;
            }
            set {
                if ((this.ValorRecibidoField.Equals(value) != true)) {
                    this.ValorRecibidoField = value;
                    this.RaisePropertyChanged("ValorRecibido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDtoDatosLiquidacion", Namespace="http://www.MillensCorp.com/types/")]
    [System.SerializableAttribute()]
    public partial class ServiceDtoDatosLiquidacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Iva {
            get {
                return this.IvaField;
            }
            set {
                if ((this.IvaField.Equals(value) != true)) {
                    this.IvaField = value;
                    this.RaisePropertyChanged("Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LiquidacionWR.ILiquidacionService")]
    public interface ILiquidacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionService/getDatosLiquidacion", ReplyAction="http://tempuri.org/ILiquidacionService/getDatosLiquidacionResponse")]
        BlockAndPass.WebService.LiquidacionWR.Liquidacion_Response getDatosLiquidacion(BlockAndPass.WebService.LiquidacionWR.Liquidacion_Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILiquidacionService/getDatosLiquidacion", ReplyAction="http://tempuri.org/ILiquidacionService/getDatosLiquidacionResponse")]
        System.Threading.Tasks.Task<BlockAndPass.WebService.LiquidacionWR.Liquidacion_Response> getDatosLiquidacionAsync(BlockAndPass.WebService.LiquidacionWR.Liquidacion_Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILiquidacionServiceChannel : BlockAndPass.WebService.LiquidacionWR.ILiquidacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiquidacionServiceClient : System.ServiceModel.ClientBase<BlockAndPass.WebService.LiquidacionWR.ILiquidacionService>, BlockAndPass.WebService.LiquidacionWR.ILiquidacionService {
        
        public LiquidacionServiceClient() {
        }
        
        public LiquidacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiquidacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiquidacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BlockAndPass.WebService.LiquidacionWR.Liquidacion_Response getDatosLiquidacion(BlockAndPass.WebService.LiquidacionWR.Liquidacion_Request request) {
            return base.Channel.getDatosLiquidacion(request);
        }
        
        public System.Threading.Tasks.Task<BlockAndPass.WebService.LiquidacionWR.Liquidacion_Response> getDatosLiquidacionAsync(BlockAndPass.WebService.LiquidacionWR.Liquidacion_Request request) {
            return base.Channel.getDatosLiquidacionAsync(request);
        }
    }
}
